apiVersion: v1
kind: Service
metadata:
  name: bloggingsystem-service
spec:
  type: LoadBalancer
  selector:
    app: bloggingsystem
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  - protocol: TCP
    port: 8081
    targetPort: 8081