apiVersion: v1
kind: Service
metadata:
  name: bloggingsystem-service
spec:
  type: NodePort
  selector:
    app: bloggingsystem
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
    - name: https
      protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30081