apiVersion: apps/v1
kind: Deployment
metadata:
  name: bloggingsystem-deployment
  labels:
    app: bloggingsystem
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bloggingsystem
  template:
    metadata:
      labels:
        app: bloggingsystem
    spec:
      containers:
      - name: bloggingsystem
        image: velscorp/bloggingsystem
        ports:
        - containerPort: 8080
        - containerPort: 8081
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Kubernetes"
        - name: ASPNETCORE_URLS
          value: "http://+:8080;https://+:8081"
        - name: ASPNETCORE_Kestrel__Certificates__Default__Password
          value: "development"
        - name: ASPNETCORE_Kestrel__Certificates__Default__Path
          value: "/https/bloggingsystem.pfx"
        - name: Ceph__Endpoint
          value: "ceph-rgw"
        - name: Ceph__EndpointPort
          value: "7480"
        - name: Ceph__EndpointHttpsPort
          value: "7481"
        - name: Ceph__AccessKey
          valueFrom:
            secretKeyRef:
              name: ceph-credentials
              key: accesskey
        - name: Ceph__SecretKey
          valueFrom:
            secretKeyRef:
              name: ceph-credentials
              key: secretkey
        - name: Ceph__BucketName
          value: "BlogImages"
        volumeMounts:
        - name: certs
          mountPath: /https
      volumes:
      - name: certs
        secret:
          secretName: bloggingsystem-certs
