services:
  bloggingsystem:
    image: ${DOCKER_REGISTRY-}bloggingsystem
    build:
      context: .
      dockerfile: BloggingSystem/Dockerfile
    restart: always
    container_name: bloggingsystem
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - ASPNETCORE_Kestrel__Certificates__Default__Password=development
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
    ports:
      - 8080:8080
      - 8081:8081
    depends_on:
      - mongodb
      - redis
      - elasticsearch
      - ceph-mon
      - ceph-mgr
      - ceph-osd
    networks:
      - bloggingsystem-net

  mongodb:
    image: mongo:latest
    restart: always
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: BlogStore
    volumes:
      - mongodata:/data/db
      - ./Docker/mongodb/init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - 27017:27017
    networks:
      - bloggingsystem-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:latest
    restart: always
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - bloggingsystem-net

  kibana:
    image: docker.elastic.co/kibana/kibana:latest
    restart: always
    container_name: kibana
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - bloggingsystem-net

  logstash:
    build:
      context: .
      dockerfile: Docker/logstash/Dockerfile
    restart: always
    container_name: logstash
    volumes:
      - ./Docker/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - 5044:5044
    depends_on:
      - mongodb
      - elasticsearch
    networks:
      - bloggingsystem-net

  redis:
    image: redis:latest
    restart: always
    container_name: redis
    volumes:
      - redisdata:/data
    ports:
      - 6379:6379
    networks:
      - bloggingsystem-net

  ceph-mon:
    image: ceph/daemon:latest-mimic
    restart: always
    container_name: ceph-mon
    command: mon
    environment:
      - MON_IP=192.168.55.2
      - CEPH_PUBLIC_NETWORK=192.168.55.0/24
    volumes:
      - cephdata:/etc/ceph
      - cephdata:/var/lib/ceph/
    ports:
      - 6789:6789
    networks:
      bloggingsystem-net:
        ipv4_address: "192.168.55.2"

  ceph-mgr:
    image: ceph/daemon:latest-mimic
    restart: always
    container_name: ceph-mgr
    command: mgr
    environment:
      - MGR_MODULE_ENABLE=dashboard
    volumes:
      - cephdata:/etc/ceph
      - cephdata:/var/lib/ceph/
    depends_on:
      - ceph-mon
    ports:
      - 7000:7000
    networks:
      - bloggingsystem-net

  ceph-osd:
    pid: host
    privileged: true
    container_name: ceph-osd
    image: ceph/daemon:v3.1.0-stable-3.1-mimic-centos-7
    command: osd_directory
    restart: always
    environment:
      LANG: en_US.utf8
      TZ: UTC
    volumes:
      - cephdata:/etc/ceph
      - cephdata:/var/lib/ceph/
    depends_on:
      - ceph-mon
    networks:
      - bloggingsystem-net

volumes:
  mongodata:
    driver: local
  esdata:
    driver: local
  redisdata:
    driver: local
  cephdata:
    driver: local

networks:
  bloggingsystem-net:
    ipam:
      driver: default
      config:
        - subnet: 192.168.55.0/24