services:
  bloggingsystem:
    image: ${DOCKER_REGISTRY-}bloggingsystem
    build:
      context: .
      dockerfile: BloggingSystem/Dockerfile
    container_name: bloggingsystem
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      - 8080:8080
      - 8081:8081
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - ASPNETCORE_Kestrel__Certificates__Default__Password=development
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
      - ./Docker/mongodb/init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_DATABASE: BlogStore

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.0
    container_name: kibana
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  logstash:
    build:
      context: .
      dockerfile: Docker/logstash/Dockerfile
    container_name: logstash
    volumes:
      - ./Docker/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      - 5044:5044

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data

  ceph:
    image: ceph/daemon:latest
    container_name: ceph
    environment:
      MON_IP: "127.0.0.1"
      CEPH_PUBLIC_NETWORK: "0.0.0.0/0"
    volumes:
      - cephdata:/var/lib/ceph
    ports:
      - 6789:6789
      - 6800-6803:6800-6803

volumes:
  mongodata:
    driver: local
  esdata:
    driver: local
  redisdata:
    driver: local
  cephdata:
    driver: local