apiVersion: apps/v1
kind: Deployment
metadata:
  name: ceph-rgw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ceph-rgw
  template:
    metadata:
      labels:
        app: ceph-rgw
    spec:
      containers:
      - name: ceph-rgw
        image: quay.io/ceph/daemon
        command: ["/opt/ceph-container/bin/entrypoint.sh", "rgw"]
        env:
        - name: RGW_FRONTENDS
          value: "beast port=7480 ssl_port=7481 ssl_certificate=/certs/bloggingsystem.crt ssl_private_key=/certs/bloggingsystem.key"
        ports:
        - containerPort: 7480
        - containerPort: 7481
        volumeMounts:
        - name: ceph-conf
          mountPath: /etc/ceph/ceph.conf
          subPath: ceph.conf
        - name: cephdata
          mountPath: /etc/ceph
        - name: cephdata
          mountPath: /var/lib/ceph/
        - name: rgw-certs
          mountPath: /certs
      volumes:
      - name: ceph-conf
        configMap:
          name: ceph-config
      - name: cephdata
        persistentVolumeClaim:
          claimName: ceph-pvc
      - name: rgw-certs
        secret:
          secretName: bloggingsystem-certs
---
apiVersion: v1
kind: Service
metadata:
  name: ceph-rgw
spec:
  type: NodePort
  selector:
    app: ceph-rgw
  ports:
    - name: http
      protocol: TCP
      port: 7480
      targetPort: 7480
      nodePort: 30480
    - name: https
      protocol: TCP
      port: 7481
      targetPort: 7481
      nodePort: 30481