apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ceph-mon
spec:
  serviceName: "ceph-mon"
  replicas: 1
  selector:
    matchLabels:
      app: ceph-mon
  template:
    metadata:
      labels:
        app: ceph-mon
    spec:
      containers:
      - name: ceph-mon
        image: ceph/daemon:latest-mimic
        command: ["/entrypoint.sh", "mon"]
        env:
          - name: MON_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: CEPH_PUBLIC_NETWORK
            value: "10.1.0.0/24"
        ports:
        - containerPort: 6789
        volumeMounts:
        - name: ceph-conf
          mountPath: /etc/ceph/ceph.conf
          subPath: ceph.conf
        - name: cephdata
          mountPath: /etc/ceph
        - name: cephdata
          mountPath: /var/lib/ceph/
        - name: ceph-logs
          mountPath: /var/log/ceph
      volumes:
      - name: cephdata
        persistentVolumeClaim:
          claimName: ceph-pvc
      - name: ceph-conf
        configMap:
          name: ceph-config
      - name: ceph-logs
        emptyDir: {}
  updateStrategy:
    type: RollingUpdate
---
apiVersion: v1
kind: Service
metadata:
  name: ceph-mon
spec:
  type: ClusterIP
  selector:
    app: ceph-mon
  ports:
    - protocol: TCP
      port: 6789
      targetPort: 6789