apiVersion: apps/v1
kind: Deployment
metadata:
  name: ceph-mgr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ceph-mgr
  template:
    metadata:
      labels:
        app: ceph-mgr
    spec:
      containers:
      - name: ceph-mgr
        image: ceph/daemon:latest-mimic
        command: ["/entrypoint.sh", "mgr"]
        env:
        - name: MGR_MODULE_ENABLE
          value: "dashboard"
        ports:
        - containerPort: 8443
        volumeMounts:
        - name: cephdata
          mountPath: /etc/ceph
        - name: cephdata
          mountPath: /var/lib/ceph/
      volumes:
      - name: cephdata
        persistentVolumeClaim:
          claimName: ceph-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: ceph-mgr
spec:
  type: NodePort
  selector:
    app: ceph-mgr
  ports:
  - protocol: TCP
    port: 8443
    targetPort: 8443
    nodePort: 30084