apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ceph-osd-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ceph-osd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ceph-osd
  template:
    metadata:
      labels:
        app: ceph-osd
    spec:
      containers:
      - name: ceph-osd
        image: ceph/daemon:latest-mimic
        command: ["osd"]
        env:
        - name: OSD_TYPE
          value: "directory"
        - name: OSD_DIRECTORY
          value: "/var/lib/ceph/osd/ceph-0"
        - name: OSD_BLUESTORE
          value: "1"
        volumeMounts:
        - name: cephdata
          mountPath: /etc/ceph
        - name: osd-data
          mountPath: /var/lib/ceph/osd/ceph-0
      volumes:
      - name: cephdata
        persistentVolumeClaim:
          claimName: ceph-osd-pvc
      - name: osd-data
        persistentVolumeClaim:
          claimName: ceph-osd-pvc
    securityContext:
      privileged: true