apiVersion: apps/v1
kind: Deployment
metadata:
  name: ceph-osd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ceph-osd
  template:
    metadata:
      labels:
        app: ceph-osd
    spec:
      containers:
      - name: ceph-osd
        image: ceph/daemon:latest-mimic
        command: ["/entrypoint.sh", "osd"]
        securityContext:
          privileged: true
        env:
        - name: OSD_TYPE
          value: "directory"
        - name: OSD_DIRECTORY
          value: "/var/lib/ceph/osd/ceph-0"
        - name: OSD_BLUESTORE
          value: "1"
        volumeMounts:
        - name: cephdata
          mountPath: /etc/ceph
        - name: cephdata
          mountPath: /var/lib/ceph/
      volumes:
      - name: cephdata
        persistentVolumeClaim:
          claimName: ceph-pvc