apiVersion: v1
kind: ConfigMap
metadata:
  name: ceph-config
data:
  ceph.conf: |
    [global]
    fsid = edc283ee-cc3c-4568-aa89-e83d170ce45f
    mon initial members = admin
    mon host = ceph-mon:6789
    osd journal size = 100
    log file = /dev/null
    osd pool default min size = 1
    osd pool default size = 1
    max open files = 655350
    cephx cluster require signatures = false
    cephx service require signatures = false
    osd max object namespace len = 64
    rgw_frontends = beast port=7480 ssl_port=7481 ssl_certificate=/certs/bloggingsystem.crt ssl_private_key=/certs/bloggingsystem.key
    rgw_verify_ssl = false
    osd max object name len = 256
  ceph.mon.keyring: |
    [mon.]
        key = AQBkQsNm62rsOhAAYnANmntSNepb9pjgzHckVw==
        caps mon = "allow *"
    [client.admin]
        key = AQBkQsNmblC8OBAAyrbxETZ5cVx8DWsW27Z+qQ==
        auid = 0
        caps mds = "allow *"
        caps mgr = "allow *"
        caps mon = "allow *"
        caps osd = "allow *"
    [client.bootstrap-mds]
        key = AQBlQsNmk6DOAxAAy+9dkcyM0JYjrqc8S40DmA==
        caps mon = "allow profile bootstrap-mds"
    [client.bootstrap-osd]
        key = AQBlQsNm8p6ZARAA9lwsUJQJmJoZ8UY8z1tfAg==
        caps mon = "allow profile bootstrap-osd"
    [client.bootstrap-rbd]
        key = AQBlQsNmLKmHChAAKhSl/P+0vVlhSOS/bEdStA==
        caps mon = "allow profile bootstrap-rbd"
    [client.bootstrap-rgw]
        key = AQBlQsNmG6P/BRAANRx7h+NZcry6uuNo2J3Jfg==
        caps mon = "allow profile bootstrap-rgw"
  ceph.mon.admin.keyring: |
    [client.admin]
        key = AQBkQsNmblC8OBAAyrbxETZ5cVx8DWsW27Z+qQ==
        auid = 0
        caps mds = "allow *"
        caps mgr = "allow *"
        caps mon = "allow *"
        caps osd = "allow *"
  keyring: |
    [mon.]
        key = AQBkQsNm62rsOhAAYnANmntSNepb9pjgzHckVw==
        caps mon = "allow *"