apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
        env:
        - name: discovery.type
          value: "single-node"
        - name: ES_JAVA_OPTS
          value: "-Xms512m -Xmx512m"
        - name: ELASTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: elasticsearch-credentials
              key: elastic_password
        - name: KIBANA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: elasticsearch-credentials
              key: kibana_password
        ports:
        - containerPort: 9200
        volumeMounts:
        # - name: elasticsearch-data
        #   mountPath: /usr/share/elasticsearch/data
        #   readOnly: false
        - name: elasticsearch-config
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
        - name: elasticsearch-certificates
          mountPath: /usr/share/elasticsearch/config/bloggingsystem.crt
          subPath: bloggingsystem.crt
        - name: elasticsearch-certificates
          mountPath: /usr/share/elasticsearch/config/bloggingsystem.key
          subPath: bloggingsystem.key
      volumes:
      - name: elasticsearch-data
        persistentVolumeClaim:
          claimName: elasticsearch-pvc
      - name: elasticsearch-config
        configMap:
          name: elasticsearch-config
      - name: elasticsearch-certificates
        secret:
          secretName: bloggingsystem-certs