services:
  bloggingsystem:
    image: ${DOCKER_REGISTRY-}bloggingsystem
    build:
      context: ..
      dockerfile: Dockerfile
    restart: always
    container_name: bloggingsystem
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerCompose
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_URLS=https://+:8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=development
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/bloggingsystem.pfx
      - Ceph__Endpoint=ceph-rgw
      - Ceph__EndpointPort=7480
      - Ceph__EndpointHttpsPort=7481
      - Ceph__AccessKey=${ACCESS_KEY}
      - Ceph__SecretKey=${SECRET_KEY}
      - Ceph__BucketName=BlogImages
    volumes:
      - ./certs:/https:ro
    ports:
      - 8080:8080
      - 8081:8081
    depends_on:
      - mongodb
      - redis
      - elasticsearch
      - ceph-mon

  mongodb:
    image: mongo:latest
    restart: always
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: BlogStore
    volumes:
      - mongodata:/data/db
      - ./mongodb/init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - 27017:27017

  elasticsearch:
    build:
      context: .
      dockerfile: elasticsearch/Dockerfile
    restart: always
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - ELASTIC_PASSWORD=development
      - KIBANA_PASSWORD=development
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibana:
    build:
      context: .
      dockerfile: kibana/Dockerfile
    restart: always
    container_name: kibana
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  redis:
    image: redis:latest
    restart: always
    container_name: redis
    volumes:
      - redisdata:/data
    ports:
      - 6379:6379

  ceph-mon:
    image: ceph/daemon:latest-mimic
    restart: always
    container_name: ceph-mon
    command: mon
    environment:
      - MON_IP=192.168.55.2
      - CEPH_PUBLIC_NETWORK=192.168.55.0/24
    volumes:
      - cephdata:/etc/ceph
      - cephdata:/var/lib/ceph/
    ports:
      - 6789:6789
    networks:
      ceph-net:
        ipv4_address: "192.168.55.2"
      default:

  ceph-mgr:
    image: ceph/daemon:latest-mimic
    restart: always
    container_name: ceph-mgr
    command: mgr
    environment:
      - MGR_MODULE_ENABLE=dashboard
    volumes:
      - cephdata:/etc/ceph
      - cephdata:/var/lib/ceph/
    ports:
      - 8443:8443
    depends_on:
      - ceph-mon
    networks:
      ceph-net:
        ipv4_address: "192.168.55.3"
      default:

  ceph-osd:
    image: ceph/daemon:latest-mimic
    restart: always
    container_name: ceph-osd
    command: osd
    pid: host
    privileged: true
    environment:
      - OSD_TYPE=directory
      - OSD_DIRECTORY=/var/lib/ceph/osd/ceph-0
      - OSD_BLUESTORE=1
    volumes:
      - cephdata:/etc/ceph
      - cephdata:/var/lib/ceph/
    depends_on:
      - ceph-mon
    networks:
      ceph-net:
        ipv4_address: "192.168.55.4"
      default:

  ceph-rgw:
    image: quay.io/ceph/daemon
    restart: always
    container_name: ceph-rgw
    command: rgw
    volumes:
      - cephdata:/etc/ceph
      - cephdata:/var/lib/ceph/
      - ./certs:/certs:ro
    ports:
      - 7480:7480
      - 7481:7481
    depends_on:
      - ceph-osd
    networks:
      ceph-net:
        ipv4_address: "192.168.55.5"
      default:

volumes:
  mongodata:
    driver: local
  esdata:
    driver: local
  redisdata:
    driver: local
  cephdata:
    driver: local

networks:
  ceph-net:
    ipam:
      driver: default
      config:
        - subnet: 192.168.55.0/24