apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
data:
  kibana.yml: |
    server.host: "0.0.0.0"
    server.shutdownTimeout: "5s"
    monitoring.ui.container.elasticsearch.enabled: true
    elasticsearch.hosts: https://elasticsearch:9200
    elasticsearch.username: "kibana_system"
    elasticsearch.password: "${KIBANA_PASSWORD}"
    elasticsearch.ssl.verificationMode: none
    elasticsearch.ssl.certificateAuthorities: /usr/share/kibana/config/bloggingsystem.crt
    server.ssl.enabled: true
    server.ssl.key: /usr/share/kibana/config/bloggingsystem.key
    server.ssl.certificate: /usr/share/kibana/config/bloggingsystem.crt