apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:8.15.0
        ports:
        - containerPort: 5601
        volumeMounts:
        - name: kibana-config-volume
          mountPath: /usr/share/kibana/config
        - name: kibana-certificates
          mountPath: /usr/share/kibana/config
      volumes:
      - name: kibana-config-volume
        configMap:
          name: kibana-config
      - name: kibana-certificates
        secret:
          secretName: bloggingsystem-certs